name-template: 'v$RESOLVED_VERSION ğŸŒˆ'
tag-template: 'v$RESOLVED_VERSION'

categories:
  - title: 'ğŸš€ Features'
    labels:
      - 'new feature'
      - 'enhancement'
  - title: 'ğŸ› Bug Fixes'
    labels:
      - 'bug fix'
  - title: 'ğŸ”§ Maintenance'
    labels:
      - 'build'
      - 'code style'
      - 'pipeline'
      - 'refactoring'
      - 'documentation'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
template: |
  ## Changes
  $CHANGES
